"""Created foreign key from task to status

Revision ID: 399f468a4651
Revises: 8628ef1ff8d1
Create Date: 2025-08-21 15:17:21.015462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399f468a4651'
down_revision: Union[str, Sequence[str], None] = '8628ef1ff8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'status_id')
    # ### end Alembic commands ###
