"""Created new table + changes for mysql

Revision ID: 8628ef1ff8d1
Revises: 82c84630706c
Create Date: 2025-08-21 15:05:18.196775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8628ef1ff8d1'
down_revision: Union[str, Sequence[str], None] = '82c84630706c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('task', 'text',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=4096),
               existing_nullable=True)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.alter_column('task', 'text',
               existing_type=sa.String(length=4096),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('task', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
